### ISSUE TITLE
Create composer cog for team compositions and profiles.

### ISSUE THREAD

**Issue by LeptoSpira** [DrBluefall/ProjectPrismarine#12]
This is going to be our first real competitive oriented cog.

## Purpose
- To provide the ability to create team comps, organize profiles, etc

## The first step
- [x] Use the template module to create a new module

There isn't a lot of information to give right at this moment.
@DrBluefall should comment some more details later.

**Comment by DrBluefall** [comment]
Ok, here's my idea for the composer module.

# Team Composer

This module will allow people to have team profiles. These profiles will contain a few things:
- A team roster of 4-6 people
- A team icon
- A team name
- A team ID (Just to make querying for teams easier.)

This module I believe should also be able to create, save, and edit weapon compositions so that teams may refer to them in the future. The `loadout.py` bin file could come in handy, since we'll likely also want to display the composition's gear in addition to the weapons.

I'll start work on a rough implementation soon. For now, maybe build on what I have here, suggest more things or a method of implementation.

**Comment by DrBluefall** [comment]
Welp, this issue is nearing it's conclusion! All that's needed now is to give the commands more robust documentation and we'll be all set!

**Comment by DrBluefall** [comment]
All documentation has been added! This issue can now be closed, and the cog can be deployed to the master bot!
